# Site
name: "Telmo Julião"
title: "Telmo Julião"
description: "Hi, my name is Telmo Julião. I'm a digital Product Designer based in sunny Lisbon, Portugal."
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
include: ["_pages"]
permalink: /:title/
baseurl: /portfolio/

# Works collection
collections:
  works:
    output: true
    permalink: /work/:name

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [Gemfile, Gemfile.lock]
